# Translation from English to Korean
eng_to_ko:
  # map
  ant_cave_2: 개미굴2
  cloud_balcony: 구름테라스
  dragon_territory: 와일드카고의 영역
  empty_house: 빈집
  fire_land_1: 불타는 땅1
  fire_land_2: 불타는 땅2
  first_barrack: 제1군영
  land_of_wild_boar: 와일드보어의 땅
  lost_time_1: 잃어버린 시간1
  monkey_swamp_3: 원숭이의 늪3
  mushroom_hills: 버섯동산
  north_forest_training_ground_2: 북쪽숲나무던전2
  north_forest_training_ground_8: 북쪽숲나무던전8
  pig_shores: 돼지의 해안가
  the_path_of_time_1_for_mage: 시간의길1(마법사)
  garden_of_green_2: 푸른 빛의 정원2
  garden_of_red_2: 붉은 빛의 정원2
  foggy_forest_for_mage: 안개낀숲(마법사)
  101_2f_east: 패션 애비뉴 서쪽구역
  black_mountain: 까막산 기슭
  disposed_flower_garden: 버려진 화원
  mu_Lung_wild_bear_area_2: 야생곰의 영토2
  forest_of_dead_trees_2: 죽숲2
  black_kentauros_area: 검은 켄타우로스의 영역
  # monster
  coolie_zombie: 쿨리좀비
  zombie_lupin: 좀비루팡
  black_axe_stump: 다크 엑스스텀프
  brown_windup_bear: 브라운테디
  cold_eye: 콜드아이
  evolved_ghost: 플래툰 크로노스
  fire_boar: 파이어보어
  green_mushroom: 초록버섯
  mushroom: 주황버섯
  pig: 돼지
  pink_windup_bear: 핑크테디
  ribbon_pig: 리본돼지
  skeleton_officer: 스켈레톤 사관
  skeleton_soldier: 스켈레톤 사병
  spike_mushroom: 뿔버섯
  wild_boar: 와일드보어
  wild_kargo: 와일드카고
  wind_single_eye_beast: 커즈아이
  zombie_mushroom: 좀비버섯
  grupin: 그루핀
  red_cellion: 샐리온
  the_book_ghost: 묘선
  blue_perfume: 블루 퍼퓸
  grizzly: 그리즐리
  panda: 팬더
  hodori: 호돌이
  moon_bunny: 월묘
  nependeath: 네펜데스
  dark_nependeath: 다크 네펜데스
  black_kentaurus: 블랙 켄타로스

# Register mobs in each maps
map_mobs_mapping:
  ant_cave_2: [spike_mushroom, zombie_mushroom]
  cloud_balcony: [pink_windup_bear, brown_windup_bear]
  dragon_territory: [wild_kargo]
  empty_house: [mushroom]
  fire_land_1: [black_axe_stump, fire_boar]
  fire_land_2: [black_axe_stump, fire_boar]
  first_barrack: [skeleton_officer, skeleton_soldier]
  land_of_wild_boar: [wild_boar]
  lost_time_1: [evolved_ghost]
  monkey_swamp_3: [zombie_lupin]
  mushroom_hills: [mushroom, green_mushroom]
  north_forest_training_ground_2: [green_mushroom, spike_mushroom]
  north_forest_training_ground_8: [wind_single_eye_beast]
  pig_shores: [pig, ribbon_pig]
  the_path_of_time_1_for_mage: [evolved_ghost]
  garden_of_green_2: [grupin]
  garden_of_red_2: [red_cellion]
  foggy_forest_for_mage: [the_book_ghost]
  101_2f_east: [blue_perfume]
  black_mountain: [hodori, moon_bunny, black_axe_stump]
  disposed_flower_garden: [nependeath, dark_nependeath]
  mu_Lung_wild_bear_area_2: [grizzly, panda]
  forest_of_dead_trees_2: [coolie_zombie]
  black_kentauros_area: [black_kentaurus]