aoe_skill:
  range_x: 350
bot:
  attack: aoe_skill
  map: forest_of_dead_trees_2
  mode: patrol
health_monitor:
  add_hp_percent: 70
  add_mp_percent: 0
  force_heal: true
key:
  add_hp: ins
  aoe_skill: "\u21E7"
  directional_attack: ''
  jump: ''
  return_home: ''
  teleport: space
patrol:
  patrol_attack_interval: 1.0
  patrol_attack_interval_random: 0.6
teleport:
  cooldown_random: 0.5
  is_use_teleport_to_walk: True
  keep_route_jump: True  
